set-option -sa terminal-features ",xterm*:RGB"
set -g default-terminal "tmux-256color"

set -g bell-action none
set -g status-position top

set -g prefix `
unbind C-b
bind ` send-prefix

set-option -g status-style bg=default
set-window-option -g mode-keys vi