;;; package --- Summary -*- lexical-binding: nil -*-
;;; Commentary:
;;; Code:

(defun adam/meow-motion/normal-define-key (&rest args)
  "Defines both `motion' and `normal' keybinds for `meow.el' using args ARGS."
  (apply 'meow-motion-define-key args)
  (apply 'meow-normal-define-key args))

(use-package meow
  :config
  (setq meow-use-clipboard t)
  (setq meow-select-on-change nil)
  (add-to-list 'meow-mode-state-list '(emms-browser-mode . motion))
  (add-to-list 'meow-mode-state-list '(mu4e-view-mode . motion))
  
  ;; Quitting is always an option...
  (global-set-key (kbd "C-s") #'adam/save-all)
  (global-set-key [remap keyboard-quit] #'adam/meow-cancel-or-mc-quit)
  (global-set-key (kbd "<escape>") #'adam/meow-cancel-or-mc-quit)
  
  (meow-leader-define-key
   '("?" . adam/lookup-panel/body)
   '("M" . adam/music-panel/body)
   '("w" . adam/window-panel/body)
   '("s" . adam/shellder/body)
   '("Z" . adam/zoomer/body)
   '("f" . adam/finder/body)
   '("l" . adam/launcher/body)
   '("z" . adam/goto/body)
   '("<SPC>" . adam/M-x)
   '("d d" . kill-whole-line)
   '("." . adam/find-file-new)
   '("y y" . adam/yank-line))  
  (adam/meow-motion/normal-define-key
   '("`" . adam/meow-mode-toggle)
   '("'" . repeat-complex-command)
   '("y" . meow-clipboard-save)
   '("d" . meow-kill)
   '("g" . meow-cancel-selection)
   '("V" . meow-line)
   '("j" . adam/j)
   '("k" . adam/k)
   '("h" . backward-char)
   '("l" . forward-char)
   '("H" . awin/move-left)
   '("J" . awin/move-down)
   '("K" . awin/move-up)
   '("L" . awin/move-right)
   '("C-f" . adam/meow-right-select)
   '("C-b" . adam/meow-left-select)
   '("w" . forward-word)
   '("b" . backward-word)
   '("M-d" . mc/mark-next-like-this)
   '("<escape>" . adam/meow-cancel-or-mc-quit))
  (meow-normal-define-key
   '("i" . meow-append)
   '("I" . (lambda () (interactive) (back-to-indentation) (meow-append)))
   '("q" . meow-quit)
   '("Q" . kmacro-start-macro-or-insert-counter)
   '("@" . kmacro-end-or-call-macro)
   '("s" . er/mark-symbol)
   '("S" . er/mark-outside-quotes)
   '("W" . er/mark-word)
   '("B" . meow-block)
   '("f" . adam/char-jump-fast)
   '("F" . flash-jump)
   '("p" . adam/paste-below)
   '("P" . adam/paste-above)
   '("c" . meow-change)
   '("o" . meow-open-below)
   '("O" . meow-open-above)
   '("?" . adam/lookup-panel/body)
   '("r" . meow-reverse)
   '("[" . adam/expand-region-char)
   '("]" . adam/shrink-region-char)
   '("a" . (lambda () (interactive) (adam/sticky-forward-char) (meow-append)))
   '("A" . (lambda () (interactive) (end-of-line) (meow-append)))
   '("x" . adam/kill-char)
   '("C-j" . adam/join-line)
   '("u" . undo)
   '("U" . undo-redo)
   '(">" . adam/indent-right)
   '("<" . adam/indent-left)
   '("=" . indent-region)
   '("C-#" . adam/comment)))

(meow-global-mode 1)

(provide 'adam-keys)
;;; adam-keys.el ends here
