* 🖥️ Portable Puter 🖥️
The is essentially my *.dotfiles* repo. It is a complete mess and filled with legacy junk that I used on previous configs with other linux distros. To be honest I don't even use half of this stuff anymore, and the only thing of *actual* value is my [[./dotfiles/.emacs.d/][emacs]] config. Everything is a trash heap of fire 🔥🔥🔥.

Run the following command to initialize.
#+BEGIN_SRC shell
./puter/scriptz/puter-linkup
#+END_SRC

Once initialized you can also run the following in emacs.
#+BEGIN_SRC emacs-lisp
(puter/linkup)
#+END_SRC

** 🤖 [[./ASTACK.md][ASTACK: Adam's Full-Stack Agentic Dark-Factory Workflow]]
Infinite productivity. Escape the permanent underclass and consume bajillions of tokens with the world's most *powerful* agentic workflow. 🚀🚀🚀

** 💾 [[./Dotfiles/][Dotfiles]]
A collection of config files to be symlinked by gnu-stow with the [[./scriptz/puter-linkup][puter-linkup]] script.

** 🔥 [[./notfiles][Notfiles]]
A bunch of current legacy scripts and configs. A quick hack to prevent things that shouldn't be linked or be placed in the shell path from being actualized. However I keep this stuff out of nostaglia and to tell myself that fumbling around with some of these esoteric configs for hours and hours was worth it. And it was worth it 🙂.

** 🧻 [[./scriptz/][Scriptz]]
A bunch of scripts that are added the shell path. Some of these are definitly [[./notfiles/][notfiles]] worthy.

** 🎨 [[./pape][Wallpapers]]
All the coolest wallpapers known to man.

** 🎮 [[./saves][Game Saves]]
Some game saves I want to keep around.
