#!/bin/sh

workspace=$(hyprctl activeworkspace -j | jq '.id')

if [ "$#" -eq 1 ]; then
    case "$1" in
        dwindle) hyprctl keyword workspace $workspace,layout:dwindle ;;
        monocle) hyprctl keyword workspace $workspace,layout:monocle ;;
        *) echo "not valid workspace format"
           exit 1;;
    esac
elif [ "$#" -eq 0 ]; then
    echo "$workspace"
else
    echo "incorrect commandline arguments"
    exit 1
fi
