#!/bin/sh

layout=$(hyprctl activeworkspace -j | jq -r '.tiledLayout')

if [ "$#" -eq 1 ]; then
    if [ "$layout" = "monocle" ]; then
        case "$1" in
            next) hyprctl dispatch layoutmsg cyclenext ;;
            prev) hyprctl dispatch layoutmsg cycleprev ;;
            *) echo "not valid cycle format"
            exit 1;;
        esac
    else
        case "$1" in
            next) hyprctl dispatch cyclenext ;;
            prev) hyprctl dispatch cyclenext prev ;;
            *) echo "not valid cycle format"
            exit 1;;
        esac
    fi
else
    echo "incorrect commandline arguments"
    exit 1
fi
