#!/bin/sh

# set -xve

if [ "$#" -eq 1 ]; then
    if [ "$1" = "-full" ]; then
        grim -g - - | tee ~/Pictures/screenshots/screenshot_$(date +%s).png | wl-copy
    else
        echo "incorrect commandline arguments"
        exit 1
    fi
else
    slurp | grim -g - - | tee ~/Pictures/screenshots/screenshot_$(date +%s).png | wl-copy
fi
