#!/bin/sh

if [ "$#" -eq 1 ]; then
    case "$1" in
        window) rofi -show window -show-icons ;;
        clipboard) cliphist list | rofi -dmenu -p "clip" | cliphist decode | wl-copy ;;
        emoji) rofi -modi emoji -show emoji ;;
        drun) rofi -show drun -show-icons ;;
        *) echo "incorrect commandline arguments"
           exit 1;;
    esac
else
    rofi -show drun -show-icons
fi
