#!/bin/sh

if [ "$#" -eq 1 ]; then
    case "$1" in
        window) rofi -show window ;;
        clipboard) cliphist list | rofi -dmenu | cliphist decode | wl-copy ;;
        emoji) rofi -modi emoji -show emoji ;;
        *) echo "incorrect commandline arguments"
           exit 1;;
    esac
else
    rofi -show drun
fi
