font_family IosevkaNerdFontMono
symbol_font Noto Color Emoji
bold_font auto
italic_font auto
bold_italic_font auto
font_size 11.0
enable_audio_bell False
background_opacity 0.9
linux_display_server wayland
map shift+insert paste_from_clipboard